Vagrant.configure("2") do |config|
  

    #Máquine que hará las funciones de Router
    config.vm.define "firewall" do |firewall|
      firewall.vm.box = "ubuntu/trusty64"
  
      firewall.vm.provider "virtualbox" do |v|
        v.memory = 256
      end

      # El Firewall tiene 3 inferfaces de Red
      firewall.vm.network "private_network", ip: "172.16.10.1", netmask: "24", 
      firewall.vm.network "private_network", ip: "172.16.20.1", netmask: "24",
      firewall.vm.network "private_network", ip: "172.16.30.1", netmask: "24", 
 

      # Movemos los ficheros para arrancar el firewall y para borrar todo
      firewall.vm.provision "file", source: "firewall.sh", destination: "/tmp/firewall.sh"
      firewall.vm.provision "file", source: "clean_firewall.sh", destination: "/tmp/clean_firewall.sh"

  
      firewall.vm.provision "shell", path: "script.sh"
  
    end
  
    # Máquina que servirá de cliente
    config.vm.define "ciente" do |cliente|
      cliente.vm.box = "ubuntu/trusty64"
  
      cliente.vm.network "private_network", ip: "172.16.20.2", netmask: "24", 

      cliente.vm.provider "virtualbox" do |v|
        v.memory = 256
      end

      cliente.vm.provision "shell", path: "script_cliente.sh"
  
    end

    #Máquina que será el servidor Web de la DMZ
    config.vm.define "dmz" do |dmz|
      dmz.vm.box = "ubuntu/trusty64"
  
      
      dmz.vm.network "private_network", ip:"172.16.30.2", netmask: "24"

      dmz.vm.provision "shell", path: "script.sh"
  
    end
  
    
  
  end