
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname ="wordpress2cfgs"

  config.vm.network "forwarded_port", guest: 80, host: 6060

  config.vm.provision "file", source:"info.php", destination: "/tmp/info.php"

  config.vm.provision "shell", path: "wordpress.sh"

end
