Vagrant.configure("2") do |config|
  

    #Máquine que hará las funciones de Router
    config.vm.define "vm1" do |vm1|
      vm1.vm.box = "ubuntu/trusty64"
  
      # Red pública
      vm1.vm.network "public_network", ip: "192.168.1.110"
      # Red local
      vm1.vm.network "public_network", ip: "172.16.20.2"

      # Movemos los ficheros para arrancar el firewall y para borrar todo
      vm1.vm.provision "file", source: "firewall.sh", destination: "/tmp/firewall.sh"
      vm1.vm.provision "file", source: "clean_firewall.sh", destination: "/tmp/clean_firewall.sh"

  
      vm1.vm.provision "shell", path: "script.sh"
  
    end
  
    # Máquina que servirá de cliente
    config.vm.define "vm2" do |vm2|
      vm2.vm.box = "ubuntu/trusty64"
  
      # Red pública
      vm2.vm.network "private_network", ip:"172.16.20.1"  
      
  
      vm2.vm.provision "shell", path: "script_cliente.sh"
  
  
    end
  
    
  
  end